### ISSUE TITLE
Only valid bearer authentication supported, reason: None

### ISSUE THREAD

**Issue by rozbrajaczpoziomow** [JayChen35/spotify-to-mp3-python#5]
I tried to run this and here's the error i got:
```
spotify_to_mp3.py:14: DeprecationWarning: You're using 'as_dict = True'.get_access_token will return the token string directly in future versions. Please adjust your code accordingly, or use get_cached_token instead.
  token = credentials.get_access_token()
HTTP Error for GET to https://api.spotify.com/v1/playlists/1KvRs5rFnFv2gHDkD91bSz returned 400 due to Only valid bearer authentication supported
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/spotipy/client.py", line 245, in _internal_call
    response.raise_for_status()
  File "/usr/local/lib/python3.7/dist-packages/requests/models.py", line 943, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://api.spotify.com/v1/playlists/1KvRs5rFnFv2gHDkD91bSz?fields=tracks%2Cnext%2Cname&additional_types=track

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "spotify_to_mp3.py", line 107, in <module>
    playlist_name = write_playlist(username, playlist_uri)
  File "spotify_to_mp3.py", line 49, in write_playlist
    results = spotify.user_playlist(username, playlist_id, fields='tracks,next,name')
  File "/usr/local/lib/python3.7/dist-packages/spotipy/client.py", line 715, in user_playlist
    return self.playlist(playlist_id, fields=fields, market=market)
  File "/usr/local/lib/python3.7/dist-packages/spotipy/client.py", line 615, in playlist
    additional_types=",".join(additional_types),
  File "/usr/local/lib/python3.7/dist-packages/spotipy/client.py", line 291, in _get
    return self._internal_call("GET", url, payload, kwargs)
  File "/usr/local/lib/python3.7/dist-packages/spotipy/client.py", line 266, in _internal_call
    headers=response.headers,
spotipy.exceptions.SpotifyException: http status: 400, code:-1 - https://api.spotify.com/v1/playlists/1KvRs5rFnFv2gHDkD91bSz?fields=tracks%2Cnext%2Cname&additional_types=track:
 Only valid bearer authentication supported, reason: None
```

**Comment by JayChen35** [comment]
Fixed this issue in the most recent PR. Thanks!
