### ISSUE TITLE
HTTP Error for GET to https://api.spotify.com/v1/playlists/ returned 400 due to Only valid bearer authentication supported

### ISSUE THREAD

**Issue by jawnjminer** [JayChen35/spotify-to-mp3-python#6]
Hey @JayChen35, I'm still experiencing the issue. Any thoughts as to why?

```
Playlist URI (excluding "spotify:playlist:"): 6PECGhMPyi4ZsGr8QmqOVE
/Users/J/Dev/spotify-to-mp3-python/spotify_to_mp3.py:14: DeprecationWarning: You're using 'as_dict = True'.get_access_token will return the token string directly in future versions. Please adjust your code accordingly, or use get_cached_token instead.
  token = credentials.get_access_token()
HTTP Error for GET to https://api.spotify.com/v1/playlists/6PECGhMPyi4ZsGr8QmqOVE returned 400 due to Only valid bearer authentication supported
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/spotipy/client.py", line 245, in _internal_call
    response.raise_for_status()
  File "/usr/local/lib/python3.9/site-packages/requests/models.py", line 943, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://api.spotify.com/v1/playlists/6PECGhMPyi4ZsGr8QmqOVE?fields=tracks%2Cnext%2Cname&additional_types=track

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/J/Dev/spotify-to-mp3-python/spotify_to_mp3.py", line 105, in <module>
    playlist_name = write_playlist(username, playlist_uri)
  File "/Users/J/Dev/spotify-to-mp3-python/spotify_to_mp3.py", line 49, in write_playlist
    results = spotify.user_playlist(username, playlist_id, fields='tracks,next,name')
  File "/usr/local/lib/python3.9/site-packages/spotipy/client.py", line 715, in user_playlist
    return self.playlist(playlist_id, fields=fields, market=market)
  File "/usr/local/lib/python3.9/site-packages/spotipy/client.py", line 611, in playlist
    return self._get(
  File "/usr/local/lib/python3.9/site-packages/spotipy/client.py", line 291, in _get
    return self._internal_call("GET", url, payload, kwargs)
  File "/usr/local/lib/python3.9/site-packages/spotipy/client.py", line 261, in _internal_call
    raise SpotifyException(
spotipy.exceptions.SpotifyException: http status: 400, code:-1 - https://api.spotify.com/v1/playlists/6PECGhMPyi4ZsGr8QmqOVE?fields=tracks%2Cnext%2Cname&additional_types=track:
 Only valid bearer authentication supported, reason: None
```

**Comment by BonneChoure** [comment]
I have the same issue here.

**Comment by LeonVortmeyer** [comment]
Just got this as well, taking a look now

**Comment by LeonVortmeyer** [comment]
Working for me now, switched to making a simple POST request as discussed in Spotify's auth protocol here: https://developer.spotify.com/documentation/general/guides/authorization-guide/

Will fork & upload once I iron it out.

**Comment by evanyoung1** [comment]
@LeonVortmeyer Im having the same issue. Did you ever figure it out?

**Comment by LeonVortmeyer** [comment]
@evanedh yes! Apologies, I’ll upload my code. You just need to follow their token request protocol defined above, but will upload the relevant section when I’m back at my desk!

**Comment by evanedh** [comment]
@LeonVortmeyer Thanks, I got the auth portion to work but now I'm getting another error. It will download the 1st song in the playlist then give this error:

```
Playlist URI (excluding "spotify:playlist:"): 6PECGhMPyi4ZsGr8QmqOVE
Writing 15 tracks to Run.txt.
Initiating download for David Bowie - Ziggy Stardust - 2012 Remaster.
[youtube] 7KEn0uOEILs: Downloading webpage
[download] Destination: Ziggy Stardust (2012 Remaster)-7KEn0uOEILs.webm
[download] 100% of 3.24MiB in 00:00
ERROR: ffprobe/avprobe and ffmpeg/avconv not found. Please install one.
Traceback (most recent call last):
  File "C:\Users\eyoun\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\youtube_dl\YoutubeDL.py", line 2115, in post_process
    files_to_delete, info = pp.run(info)
  File "C:\Users\eyoun\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\youtube_dl\postprocessor\ffmpeg.py", line 272, in run
    filecodec = self.get_audio_codec(path)
  File "C:\Users\eyoun\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\youtube_dl\postprocessor\ffmpeg.py", line 166, in get_audio_codec
    raise PostProcessingError('ffprobe/avprobe and ffmpeg/avconv not found. Please install one.')
youtube_dl.utils.PostProcessingError: ffprobe/avprobe and ffmpeg/avconv not found. Please install one.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Users\eyoun\Desktop\spotify-to-mp3-python-master\spotify_to_mp3.py", line 118, in <module>
    find_and_download_songs(reference_file)
  File "c:\Users\eyoun\Desktop\spotify-to-mp3-python-master\spotify_to_mp3.py", line 94, in find_and_download_songs
    ydl.download([best_url])
  File "C:\Users\eyoun\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\youtube_dl\YoutubeDL.py", line 2068, in download
    res = self.extract_info(
  File "C:\Users\eyoun\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\youtube_dl\YoutubeDL.py", line 808, in extract_info
    return self.__extract_info(url, ie, download, extra_info, process)
  File "C:\Users\eyoun\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\youtube_dl\YoutubeDL.py", line 815, in wrapper
    return func(self, *args, **kwargs)
  File "C:\Users\eyoun\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\youtube_dl\YoutubeDL.py", line 847, in __extract_info
    return self.process_ie_result(ie_result, download, extra_info)
  File "C:\Users\eyoun\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\youtube_dl\YoutubeDL.py", line 881, in process_ie_result
    return self.process_video_result(ie_result, download=download)
  File "C:\Users\eyoun\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\youtube_dl\YoutubeDL.py", line 1692, in process_video_result
    self.process_info(new_info)
  File "C:\Users\eyoun\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\youtube_dl\YoutubeDL.py", line 2050, in process_info
    self.post_process(filename, info_dict)
  File "C:\Users\eyoun\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\youtube_dl\YoutubeDL.py", line 2117, in post_process
    self.report_error(e.msg)
  File "C:\Users\eyoun\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\youtube_dl\YoutubeDL.py", line 628, in report_error
    self.trouble(error_message, tb)
  File "C:\Users\eyoun\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\youtube_dl\YoutubeDL.py", line 598, in trouble
    raise DownloadError(message, exc_info)
youtube_dl.utils.DownloadError: ERROR: ffprobe/avprobe and ffmpeg/avconv not found. Please install one.
```

**Comment by evanyoung1** [comment]
Finally got it working, had it reinstall ffmpeg. Thanks!
